permissions:
  contents: write

on:
  push:

jobs:
  compile-bitchat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: assemble bitchat.s
        run: as src/bitchat/bitchat.s -o bitchat.o

      - name: assemble printing.s
        run: as src/bitchat/printing.s -o printing.o

      - name: compile bitchat.c and link
        run: gcc src/bitchat/bitchat.c bitchat.o printing.o -o bitchat.out -lm

      - name: install github cli
        run: sudo apt-get install -y gh

      - name: upload binary to 'latest' release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release view latest \
            || gh release create latest --title "Latest" --notes "Automated build"

          gh release upload latest bitchat.out --clobber


  compile-training:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: compile training.c
        run: gcc -g -Wall -Wextra src/training/training.c -o training.out -lm

      - name: install github cli
        run: sudo apt-get install -y gh

      - name: upload binary to 'latest' release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release view latest \
            || gh release create latest --title "Latest" --notes "Automated build"

          gh release upload latest training.out --clobber
